sudo: false
language: python
python:
  - "2.7"
  - "2.6"
install: pip install -r requirements.txt
before_script:
  - pip install coverage
  - pip install python-coveralls
  - pip install pep8
  - cp travis-ci/manage.py manage.py
script:
  - pep8 course_grader/
  - coverage run --source=course_grader/ manage.py test course_grader
after_script:
  - coveralls
notifications:
  webhooks:
      urls:
        - https://yarn.cac.washington.edu/rest/botalyst/v1/travis-ci
