version: '2'

services:
  app:
    environment:
      - ENV=localdev
      - PORT=8000
      - AUTH=SAML_MOCK
    restart: always
    container_name: app
    build:
      context: .
    volumes:
      - ./course_grader:/app/course_grader
    ports:
      - "8000:8000"
