version: '3.4'

services:
  app:
    build:
      context: .
      target: app-container
    restart: always
    container_name: course_grader_app
    environment:
      ENV: localdev
      AUTH: SAML_MOCK
    volumes:
      - ./course_grader:/app/course_grader
      - statics-volume:/static
    ports:
      - "${RUNSERVER_PORT:-8000}:8000"
    stdin_open: true
    tty: true
  node-bundler:
    build:
      context: .
      target: node-bundler
    restart: always
    container_name: course_grader_node
    ports:
      - "${BUNDLE_ANALYZER_PORT:-8888}:8888" # Required when environment.BUNDLE_ANALYZER is true
    environment:
      NODE_ENV: development
      ENV: localdev
      VUE_DEVTOOLS: "True"
      BUNDLE_ANALYZER: "True"
    volumes:
      - ./course_grader:/app/course_grader # expose main django app so vite can output bundles here
      - ./course_grader_vue:/app/course_grader_vue
      - statics-volume:/static
    command: npm run watch
    stdin_open: true
    tty: true
volumes:
  statics-volume:

