# Copyright 2021 UW-IT, University of Washington
# SPDX-License-Identifier: Apache-2.0

# Generated by Django 2.0.13 on 2019-10-21 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_grader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_override_grade',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grade',
            name='duplicate_code',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='gradeimport',
            name='source',
            field=models.CharField(choices=[('canvas', 'Canvas Gradebook'), ('catalyst', 'Catalyst GradeBook')], max_length=20),
        ),
        migrations.AlterField(
            model_name='importconversion',
            name='scale',
            field=models.CharField(choices=[('ug', 'Undergraduate Scale (4.0-0.7)'), ('gr', 'Graduate Scale (4.0-1.7)'), ('pf', 'School of Medicine Pass/No Pass'), ('cnc', 'Credit/No Credit Scale'), ('hpf', 'Honors/High Pass/Pass/Fail Scale')], max_length=5),
        ),
    ]
