# Generated by Django 2.0.13 on 2019-11-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_grader', '0003_auto_20191030_2152'),
    ]

    operations = [
        migrations.RenameField(
            model_name='importconversion',
            old_name='grading_standard_id',
            new_name='grading_scheme_id',
        ),
        migrations.RenameField(
            model_name='importconversion',
            old_name='grading_standard_name',
            new_name='grading_scheme_name',
        ),
        migrations.AlterField(
            model_name='importconversion',
            name='scale',
            field=models.CharField(choices=[('ug', 'Undergraduate Scale (4.0-0.7)'), ('gr', 'Graduate Scale (4.0-1.7)'), ('pf', 'School of Medicine Pass/No Pass Scale'), ('cnc', 'Credit/No Credit Scale'), ('hpf', 'Honors/High Pass/Pass/Fail Scale')], max_length=5),
        ),
    ]
