# Generated by Django 2.2.23 on 2021-05-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_grader', '0004_auto_20191106_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeimport',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='gradeimport',
            name='source',
            field=models.CharField(choices=[('canvas', 'Canvas Gradebook'), ('catalyst', 'Catalyst GradeBook'), ('csv', 'CSV File')], max_length=20),
        ),
    ]
