# Generated by Django 2.2.24 on 2021-07-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_grader', '0005_auto_20210516_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeimport',
            name='accepted_date',
            field=models.DateTimeField(null=True),
        ),
    ]
