# Generated by Django 2.2.24 on 2021-11-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_grader', '0006_gradeimport_accepted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeimport',
            name='file_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
