# Generated by Django 2.2.24 on 2021-11-03 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_grader', '0007_auto_20211103_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradeimport',
            name='file_path',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='gradeimport',
            name='file_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
